-- Generated by scripts/generate-contracts.ts. Do not edit.
-- Contract SHA-256: 0453c8e661a77bc053254c67b1fb90bf19309bc8af5f5190ecf38c5f205720d6

CREATE SCHEMA IF NOT EXISTS keynes;

CREATE OR REPLACE FUNCTION keynes.define_resource_type(input jsonb)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, keynes_internal
AS $$
  SELECT keynes_internal.apply_command('defineResource', input);
$$;

CREATE OR REPLACE FUNCTION keynes.create_budget(input jsonb)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, keynes_internal
AS $$
  SELECT keynes_internal.apply_command('createBudget', input);
$$;

CREATE OR REPLACE FUNCTION keynes.request(input jsonb)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, keynes_internal
AS $$
  SELECT keynes_internal.apply_command('requestBudget', input);
$$;

CREATE OR REPLACE FUNCTION keynes.settle(input jsonb)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, keynes_internal
AS $$
  SELECT keynes_internal.apply_command('settleBudget', input);
$$;

CREATE OR REPLACE FUNCTION keynes.get_budget(input jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, keynes_internal
AS $$
BEGIN
  RETURN keynes_internal.get_budget(input);
  EXCEPTION
    WHEN SQLSTATE 'K0001' THEN
      RETURN jsonb_build_object(
        'ok', false,
        'error', SQLERRM::jsonb
      );
END;
$$;
