export const REQUIRED_POSTGRESQL_SYSTEM_SCENARIOS = {
  "packages/postgresql/test/integration/installation.test.ts": [
    "native PostgreSQL installation installs a fresh target atomically",
    "native PostgreSQL installation returns an exact no-op result without changing installed state",
    "native PostgreSQL installation rejects an unsupported PostgreSQL version before mutation",
    "native PostgreSQL installation rejects an operator without installation privilege before mutation",
    "native PostgreSQL installation rejects missing owner and application roles",
    "native PostgreSQL installation rejects role login and database privilege contract violations",
    "native PostgreSQL installation rejects an application role with inherited owner-role access",
    "native PostgreSQL installation rejects an incompatible partial target without repairing it",
    "native PostgreSQL installation classifies two empty Keynes schemas as incompatible live state",
    "native PostgreSQL installation rejects a migration-byte mismatch without changing the target",
    "native PostgreSQL installation rejects a migration contract-digest mismatch",
    "native PostgreSQL installation rejects a contract mismatch without changing the target",
    "native PostgreSQL installation rolls back every migration after an injected failure",
    "native PostgreSQL installation rejects a changed live function body during exact recheck",
    "native PostgreSQL installation rejects changed live function security properties",
    "native PostgreSQL installation rejects live object, permission, ownership, and ACL drift",
  ],
  "packages/postgresql/test/integration/recheck.test.ts": [
    "PostgreSQL exact recheck and application-role conformance rechecks the exact graph read-only",
    "PostgreSQL exact recheck and application-role conformance checks the server, checksums, contract, and complete object inventory",
    "PostgreSQL exact recheck and application-role conformance checks owners, bodies, languages, security, and fixed search paths",
    "PostgreSQL exact recheck and application-role conformance checks bootstrap permissions and schema and function ACLs",
    "PostgreSQL exact recheck and application-role conformance allows the application role to call exactly the five public functions",
    "PostgreSQL exact recheck and application-role conformance denies private and unsupported function access without changing state",
  ],
  "packages/postgresql/test/system/budget-lifecycle.test.ts": [
    "Budget lifecycle defines a Resource type without creating Budget quantity",
    "Budget lifecycle preserves definition identity and distinguishes replay from redefinition",
    "Budget lifecycle returns canonical Resource definition errors",
    "Budget lifecycle completes one funded child lifecycle and reads its root-lineage history",
  ],
  "packages/postgresql/test/system/installation.test.ts": [
    "PostgreSQL installation installs explicit principal permission records",
    "PostgreSQL installation installs the current graph and rechecks it without changes",
    "PostgreSQL installation rejects a contract digest mismatch before installation",
    "PostgreSQL installation rejects migration byte drift before applying it",
    "PostgreSQL installation rejects an installed-object mismatch after fresh migration",
    "PostgreSQL installation rolls back '0001-storage' atomically when its final statement fails",
    "PostgreSQL installation rolls back '0002-budget' atomically when its final statement fails",
    "PostgreSQL installation rolls back '0003-public' atomically when its final statement fails",
    "PostgreSQL installation rolls back '0004-policy' atomically when its final statement fails",
  ],
  "packages/postgresql/test/system/contention.test.ts": [
    "native PostgreSQL contention funds at most one sibling after proving the second request waits",
    "native PostgreSQL contention rejects a request that waits behind a committed settlement seal",
    "native PostgreSQL contention orders a waiting settlement after the committed request",
    "native PostgreSQL contention returns the stored result when a matching command waits for commit",
  ],
  "packages/postgresql/test/system/embedded-transactions.test.ts": [
    "embedded PostgreSQL caller-owned transactions commits an approved request and application outbox row together",
    "embedded PostgreSQL caller-owned transactions leaves neither Budget state nor outbox state after explicit rollback",
    "embedded PostgreSQL caller-owned transactions rolls back Keynes when the application write fails after approval",
    "embedded PostgreSQL caller-owned transactions commits a denial without creating application work",
    "embedded PostgreSQL caller-owned transactions returns invalid_command for malformed input without opening application work",
    "embedded PostgreSQL caller-owned transactions uses the caller-owned transaction lifecycle",
    "embedded PostgreSQL caller-owned transactions keeps a pending child and outbox row invisible to another session",
    "embedded PostgreSQL caller-owned transactions makes the child and outbox row visible after the caller commits",
    "embedded PostgreSQL caller-owned transactions leaves neither child nor outbox row visible after the caller rolls back",
    "embedded PostgreSQL caller-owned transactions allows a rolled-back command identity to be reused and committed",
    "embedded PostgreSQL caller-owned transactions returns the committed result when another session replays exactly",
    "embedded PostgreSQL caller-owned transactions rejects conflicting command reuse without changing committed state",
  ],
  "packages/postgresql/test/system/replay.test.ts": [
    "command replay recovers all four canonical results across principals without duplicate history",
    "command replay replays a structurally equal command across principals despite object key order",
    "command replay recovers Resource definition after its committed response is lost",
    "command replay recovers root allocation after its committed response is lost",
    "command replay recovers an approved request after its committed response is lost",
    "command replay recovers settlement after its committed response is lost",
    "command replay rejects changed bodies for each mutation, including across principals",
    "command replay rejects reuse by a different operation",
    "command replay rejects reuse against a different target",
  ],
  "packages/postgresql/test/system/request-denial.test.ts": [
    "Budget request denial denies one unavailable Resource without changing the parent",
    "Budget request denial denies a multi-Resource envelope without reserving its fundable part",
    "Budget request denial conserves 100 sibling overlaps through public serialization, not multi-connection contention",
    "Budget request denial rejects malformed, duplicate, and caller-selected funding envelopes",
    "Budget request denial rejects a Resource type that has not been defined before evaluating funding",
    "Budget request denial rejects a request after its parent becomes inactive",
    "Budget request denial keeps request, settlement, and read permissions independent",
  ],
  "packages/postgresql/test/system/policy-request.test.ts": [
    "PostgreSQL governed Policy requests preserves root Policies created with a contract-valid non-RFC UUID",
    "PostgreSQL governed Policy requests enforces Policies for a contract-valid non-RFC request command UUID",
    "PostgreSQL governed Policy requests approves within the Policy ceiling and records canonical evidence",
    "PostgreSQL governed Policy requests denies above the Policy ceiling without reserving or creating a child",
    "PostgreSQL governed Policy requests attaches only the explicit child Policy set and evaluates it on the next request",
    "PostgreSQL governed Policy requests rejects a root Policy declaration outside the receiving Budget holdings",
    "PostgreSQL governed Policy requests rejects a child Policy declaration outside the receiving child holdings",
    "PostgreSQL governed Policy requests approves an ungoverned parent request with child Policies without parent Policy evidence",
    "PostgreSQL governed Policy requests preserves exact no-Policy bytes and legacy Resource UUID ordering",
    "PostgreSQL governed Policy requests orders effective ceilings and tied reasons by canonical text, not Resource UUID",
    "PostgreSQL governed Policy requests keeps governed state pending until the caller commits",
    "PostgreSQL governed Policy requests rolls back governed evidence, reservation, child, history, and command identity",
    "PostgreSQL governed Policy requests locks an unrequested declared availability holding in Resource UUID order",
  ],
  "packages/postgresql/test/system/policy-conformance.test.ts": [
    "PostgreSQL Policy runtime conformance executes every shared runtime conformance program through the installed renderer",
    "PostgreSQL Policy runtime conformance keeps nested boolean rendering linear",
  ],
  "packages/postgresql/test/system/policy-replay.test.ts": [
    "PostgreSQL governed Policy replay returns the exact stored result, evidence, and Context",
    "PostgreSQL governed Policy replay ignores changed availability, an external fact, and an unrelated Policy revision",
    "PostgreSQL governed Policy replay rejects command identity reuse with changed Context without changing state",
    "PostgreSQL governed Policy replay rejects command identity reuse with changed child Policies without changing state",
    "PostgreSQL governed Policy replay returns before reading the parent Policy snapshot or invoking the evaluator",
  ],
  "packages/postgresql/test/system/policy-security.test.ts": [
    "PostgreSQL Policy security rejects a malformed durable program with a sanitized invalid_policy error and no state",
    "PostgreSQL Policy security rejects a direct durable aggregate in the first CASE condition",
    "PostgreSQL Policy security rejects a direct durable aggregate in the later CASE condition",
    "PostgreSQL Policy security rejects a direct durable aggregate in the first CASE result",
    "PostgreSQL Policy security rejects a direct durable aggregate in the later CASE result",
    "PostgreSQL Policy security rejects a direct durable aggregate in the CASE else result",
    "PostgreSQL Policy security rejects a direct durable aggregate in the nested second coalesce argument",
    "PostgreSQL Policy security rejects a direct durable aggregate in the nested later coalesce argument",
    "PostgreSQL Policy security accepts a direct durable aggregate in first coalesce argument",
    "PostgreSQL Policy security accepts a direct durable aggregate in least",
    "PostgreSQL Policy security accepts a direct durable aggregate in greatest",
    "PostgreSQL Policy security rejects canonical SQL that does not match the durable program without executing it",
    "PostgreSQL Policy security rejects a noncanonical Policy name before mutation",
    "PostgreSQL Policy security rejects an invalid Policy revision before mutation",
    "PostgreSQL Policy security rejects a noncanonical Policy reason before mutation",
    "PostgreSQL Policy security rejects duplicate Policy names before mutation",
    "PostgreSQL Policy security rejects Policy output Resources outside its declared input Resources",
    "PostgreSQL Policy security rejects a context reference outside the Policy contextSchema",
    "PostgreSQL Policy security rejects a Policy canonical source over the per-Policy byte limit",
    "PostgreSQL Policy security rejects a Policy set over the aggregate canonical source byte limit",
    "PostgreSQL Policy security filters requested and available rows to each Policy input declaration",
    "PostgreSQL Policy security rejects duplicate result Resources as invalid_result",
    "PostgreSQL Policy security pins every security-definer search path to trusted schemas with pg_temp last",
    "PostgreSQL Policy security prevents the application role from reading or invoking private Policy authority",
    "PostgreSQL Policy security rejects invalid generated result rows with stable sanitized details and no mutation",
    "PostgreSQL Policy security maps generated-query failure to stable sanitized details and rolls back",
    "PostgreSQL Policy security maps generated numeric overflow to arithmetic_overflow and rolls back",
    "PostgreSQL Policy security maps aggregate transition overflow to arithmetic_overflow and rolls back",
    "PostgreSQL Policy security rejects noncanonical decimal literal precision before evaluation",
    "PostgreSQL Policy security rejects a contextSchema member with non-object",
    "PostgreSQL Policy security rejects a contextSchema member with array",
    "PostgreSQL Policy security rejects a contextSchema member with extra key",
    "PostgreSQL Policy security rejects a contextSchema member with invalid name",
    "PostgreSQL Policy security rejects a contextSchema member with invalid type",
    "PostgreSQL Policy security rejects a contextSchema member with invalid nullability",
    "PostgreSQL Policy security rejects a contextSchema member with duplicate name",
    "PostgreSQL Policy security accepts contextSchema names in canonical C byte order",
    "PostgreSQL Policy security returns invalid_command for malformed createBudget identifiers",
    "PostgreSQL Policy security returns invalid_command for malformed requestBudget identifiers",
    "PostgreSQL Policy security rejects negative integer Policy context before evaluation and rolls back",
    "PostgreSQL Policy security rolls back the complete governed command at after_command_binding",
    "PostgreSQL Policy security rolls back the complete governed command at before_policy_evaluation",
    "PostgreSQL Policy security rolls back the complete governed command at after_policy_evaluation",
    "PostgreSQL Policy security rolls back the complete governed command at after_policy_evidence",
    "PostgreSQL Policy security rolls back the complete governed command at after_domain_mutation",
    "PostgreSQL Policy security rolls back the complete governed command at after_history_insertion",
    "PostgreSQL Policy security rolls back the complete governed command at after_result_storage",
  ],
  "packages/postgresql/test/system/rollback.test.ts": [
    "command rollback rolls back Resource definition checkpoints",
    "command rollback rolls back root allocation facts, result, and history",
    "command rollback rolls back child reservation, result, and history",
    "command rollback rolls back usage, result, and settlement history",
  ],
  "packages/postgresql/test/system/settlement.test.ts": [
    "Budget settlement keeps a sealed parent settling until its open descendant settles",
    "Budget settlement resolves missing usage and records an exact known repeat as a no-op",
    "Budget settlement returns a reusable child allocation in full after settlement",
    "Budget settlement isolates child overage without charging its parent or sibling",
    "Budget settlement bounds settled nested charges before returning them to an ancestor",
    "Budget settlement settles a subset while keeping an omitted Resource unresolved",
    "Budget settlement sorts multiple isolated deficits by Resource identity",
    "Budget settlement rejects derived arithmetic overflow without committing settlement",
  ],
} as const;
