import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

import {
  applyGeneratedOutputs,
  loadContract,
  type LoadedContract,
} from "@keynes/contracts";
import { compile } from "json-schema-to-typescript";
import { format } from "oxfmt";

import { renderClient, renderValidators } from "./render.ts";

const LEGACY_GENERATED_HEADER =
  "// Generated by scripts/generate-contracts.ts. Do not edit.";
const GENERATED_TYPESCRIPT_HEADER =
  "// Generated from contracts/. Do not edit.";

export interface GenerateSdkOptions {
  readonly check: boolean;
  readonly contract: LoadedContract;
  readonly repositoryRoot?: string;
}

export async function generateSdk(options: GenerateSdkOptions): Promise<void> {
  const repositoryRoot = options.repositoryRoot ?? defaultRepositoryRoot();
  if (!isSchemaDocument(options.contract.schema)) {
    throw new Error("schema must be a JSON Schema document");
  }
  const types = await compile(options.contract.schema, "KeynesBudgetContract", {
    bannerComment: LEGACY_GENERATED_HEADER,
    style: { singleQuote: false },
    unreachableDefinitions: true,
  });
  const formattedTypes = await formatSource("types.ts", `${types.trim()}\n`);
  const formattedValidators = await formatSource(
    "validators.ts",
    renderValidators(options.contract.definitions, options.contract.source),
  );
  const formattedClient = await formatSource(
    "client.ts",
    renderClient(options.contract.source, options.contract.digest),
  );

  applyGeneratedOutputs({
    check: options.check,
    outputRoot: resolve(repositoryRoot, "packages/sdk"),
    outputs: new Map([
      ["src/generated/client.ts", formattedClient],
      ["src/generated/types.ts", formattedTypes],
      ["src/generated/validators.ts", formattedValidators],
    ]),
    generatedDirectories: [{ path: "src/generated", accepts: () => true }],
  });
}

async function formatSource(path: string, source: string): Promise<string> {
  const result = await format(
    path,
    source.replace(LEGACY_GENERATED_HEADER, GENERATED_TYPESCRIPT_HEADER),
    { printWidth: 80 },
  );
  const error = result.errors.find(
    (diagnostic) => diagnostic.severity === "Error",
  );
  if (error !== undefined) {
    throw new Error(
      `cannot format generated ${path}: ${error.message ?? "parse error"}`,
    );
  }
  return result.code;
}

function isSchemaDocument(
  value: unknown,
): value is Parameters<typeof compile>[0] {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function defaultRepositoryRoot(): string {
  return fileURLToPath(new URL("../../../", import.meta.url));
}

if (resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: { check: { type: "boolean" } },
    strict: true,
  });
  const repositoryRoot = defaultRepositoryRoot();
  await generateSdk({
    check: values.check === true,
    contract: loadContract(resolve(repositoryRoot, "packages/contracts")),
    repositoryRoot,
  });
}
