import { resolve } from "node:path";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

import {
  applyGeneratedOutputs,
  contractFieldOrder,
  loadContract,
  type LoadedContract,
} from "@keynes/database";
import { compile } from "json-schema-to-typescript";
import { format } from "oxfmt";

import {
  renderClient,
  renderValidators,
  renderRuntime,
} from "@keynes/database/generation";

const LEGACY_GENERATED_HEADER =
  "// Generated by scripts/generate-contracts.ts. Do not edit.";
const GENERATED_TYPESCRIPT_HEADER =
  "// Generated from contracts/. Do not edit.";

export interface GenerateSdkOptions {
  readonly check: boolean;
  readonly contract: LoadedContract;
  readonly repositoryRoot?: string;
}

export async function generateSdk(options: GenerateSdkOptions): Promise<void> {
  const repositoryRoot = options.repositoryRoot ?? defaultRepositoryRoot();
  if (!isSchemaDocument(options.contract.schema)) {
    throw new Error("schema must be a JSON Schema document");
  }
  const types = await compile(options.contract.schema, "KeynesBudgetContract", {
    bannerComment: LEGACY_GENERATED_HEADER,
    maxItems: 4,
    style: { singleQuote: false },
    unreachableDefinitions: true,
  });
  const formattedTypes = await formatSource("types.ts", `${types.trim()}\n`);
  const formattedValidators = await formatSource(
    "validators.ts",
    renderValidators(options.contract.definitions, options.contract.source),
  );
  const formattedClient = await formatSource(
    "client.ts",
    renderClient(
      options.contract.source,
      options.contract.digest,
      options.contract.remoteDigest,
      contractFieldOrder(options.contract.definitions),
    ),
  );
  applyGeneratedOutputs({
    check: options.check,
    outputRoot: resolve(repositoryRoot, "packages/sdk"),
    outputs: new Map([
      ["src/generated/client.ts", formattedClient],
      ["src/generated/types.ts", formattedTypes],
      ["src/generated/validators.ts", formattedValidators],
      [
        "src/command-executor.ts",
        stage("src/command-executor.ts", "../generated/", "./generated/"),
      ],
      [
        "src/generated/runtime.ts",
        await formatSource("runtime.ts", renderRuntime()),
      ],
      [
        "src/generated/decision-evidence.ts",
        stage("src/sqlite/decision-evidence.ts", "../../generated/", "./"),
      ],
    ]),
    generatedDirectories: [{ path: "src/generated", accepts: () => true }],
  });

  function stage(path: string, before: string, after: string): string {
    const source = readFileSync(
      resolve(repositoryRoot, "packages/database", path),
      "utf8",
    );
    return `// Generated from packages/database/${path}. Do not edit.\n${source.replaceAll(before, after)}`;
  }
}

async function formatSource(path: string, source: string): Promise<string> {
  const result = await format(
    path,
    source.replace(LEGACY_GENERATED_HEADER, GENERATED_TYPESCRIPT_HEADER),
    { printWidth: 80 },
  );
  const error = result.errors.find(
    (diagnostic) => diagnostic.severity === "Error",
  );
  if (error !== undefined) {
    throw new Error(
      `cannot format generated ${path}: ${error.message ?? "parse error"}`,
    );
  }
  return result.code;
}

function isSchemaDocument(
  value: unknown,
): value is Parameters<typeof compile>[0] {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function defaultRepositoryRoot(): string {
  return fileURLToPath(new URL("../../../", import.meta.url));
}

if (resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: { check: { type: "boolean" } },
    strict: true,
  });
  const repositoryRoot = defaultRepositoryRoot();
  await generateSdk({
    check: values.check === true,
    contract: loadContract(resolve(repositoryRoot, "packages/database")),
    repositoryRoot,
  });
}
