export const SDK_PRODUCTION_MODULES = [
  "result-mapping",
  "budget-request-options",
  "budget",
  "command-executor",
  "decision-evidence",
  "generated/client",
  "generated/types",
  "generated/runtime",
  "generated/validators",
  "index",
  "keynes",
  "policy",
  "replay",
  "request-serialization",
  "resource-binding",
  "resource-definition-binding",
  "resources",
  "remote/result-mapping",
  "remote/public-types",
  "remote/references",
  "sdk-errors",
] as const;
