export const SDK_PRODUCTION_MODULES = [
  "budget-projection",
  "budget-request-options",
  "budget",
  "command-executor",
  "generated/client",
  "generated/policy-profile",
  "generated/policy-types",
  "generated/types",
  "generated/validators",
  "index",
  "keynes",
  "local/runtime",
  "local/install",
  "local/pglite-command-executor",
  "policy/authoring",
  "policy/canonicalize",
  "policy/compile",
  "policy/normalize-expression",
  "policy/normalize",
  "policy/parse",
  "policy/validate",
  "replay",
  "resource-binding",
  "resource-definition-binding",
  "resources",
  "remote/budget",
  "remote/connection-options",
  "remote/errors",
  "remote/postgresql-command-executor",
  "remote/public-types",
  "remote/references",
  "remote/retry",
  "sdk-errors",
] as const;

export const SDK_PRODUCTION_ASSETS = [
  "local/assets/0001-baseline.sql",
  "local/assets/installation-record.json",
] as const;
