import type { LoadedPolicyProfile } from "@keynes/contracts";

const EXPECTED_POSTGRES_OBJECTS = [
  "schema:keynes_internal",
  "schema:keynes",
  "table:keynes_internal.schema_migrations",
  "table:keynes_internal.installation_identity",
  "table:keynes_internal.principal_permissions",
  "table:keynes_internal.commands",
  "table:keynes_internal.resource_types",
  "table:keynes_internal.budgets",
  "table:keynes_internal.budget_resources",
  "table:keynes_internal.budget_history_streams",
  "table:keynes_internal.budget_history_entries",
  "table:keynes_internal.remote_role_mappings",
  "table:keynes_internal.remote_credential_audit",
  "table:keynes_internal.remote_budget_references",
  "table:keynes_internal.remote_operations",
  "table:keynes_internal.remote_history_cursors",
  "function:keynes_internal.raise_domain_error(error_code text,error_details jsonb)",
  "function:keynes_internal.checkpoint(checkpoint_name text)",
  "function:keynes_internal.invalid_command(operation_name text,issue_path text,issue_rule text)",
  "function:keynes_internal.canonical_envelope(operation_name text,value jsonb,issue_path text,allow_null boolean)",
  "function:keynes_internal.event_uuid(seed text)",
  "function:keynes_internal.budget_is_settled(selected_tenant uuid,selected_budget uuid)",
  "function:keynes_internal.subtree_observed(selected_tenant uuid,selected_budget uuid,selected_resource uuid)",
  "function:keynes_internal.budget_charge(selected_tenant uuid,selected_budget uuid,selected_resource uuid)",
  "function:keynes_internal.assert_safe_accounting(selected_tenant uuid,changed_budget uuid,operation_name text)",
  "function:keynes_internal.budget_projection(selected_tenant uuid,selected_budget uuid)",
  "function:keynes_internal.append_history(selected_tenant uuid,selected_stream uuid,selected_command uuid,selected_kind text,selected_subject uuid,details jsonb)",
  "function:keynes_internal.apply_command(operation_name text,input jsonb)",
  "function:keynes_internal.apply_command_v0004(operation_name text,input jsonb)",
  "function:keynes_internal.canonical_resource_definition_v0005(operation_name text,value jsonb,issue_path text)",
  "function:keynes_internal.canonical_root_resources_v0005(operation_name text,value jsonb,issue_path text)",
  "function:keynes_internal.apply_define_resource_v0005(input jsonb)",
  "function:keynes_internal.apply_create_budget_v0005(input jsonb)",
  "function:keynes_internal.remote_error_v0006(error_code text,operation_name text)",
  "function:keynes_internal.remote_token_v0006(token_prefix text,token_seed text)",
  "function:keynes_internal.set_remote_identity_v0006()",
  "function:keynes_internal.remote_budget_reference_v0006(selected_tenant uuid,selected_budget uuid)",
  "function:keynes_internal.remote_budget_id_v0006(selected_tenant uuid,reference_value text,operation_name text)",
  "function:keynes_internal.remote_resource_id_v0006(selected_tenant uuid,resource_name text,operation_name text)",
  "function:keynes_internal.remote_named_amounts_v0006(selected_tenant uuid,selected_budget uuid,values_json jsonb,operation_name text,input_field text,allow_empty boolean)",
  "function:keynes_internal.remote_project_json_v0006(selected_tenant uuid,value_json jsonb)",
  "function:keynes_internal.remote_safe_error_v0006(operation_name text,error_json jsonb)",
  "function:keynes_internal.remote_invalid_v0006(operation_name text,issue_path text,issue_rule text)",
  "function:keynes_internal.remote_operation_lock_key_v0006(selected_tenant uuid,operation_key_value text)",
  "function:keynes_internal.remote_validate_input_v0006(operation_name text,input jsonb)",
  "function:keynes_internal.remote_apply_command_v0006(operation_name text,input jsonb)",
  "function:keynes_internal.remote_get_budget_v0006(input jsonb)",
  "function:keynes_internal.remote_get_budget_history_page_v0006(input jsonb)",
  "function:keynes_internal.remote_open_budget_v0006(input jsonb)",
  "function:keynes_internal.remote_recover_operation_v0006(input jsonb)",
  "function:keynes_internal.remote_get_compatibility_v0006(input jsonb)",
  "function:keynes_internal.remote_login_oid_v0006(login_role name)",
  "function:keynes_internal.register_remote_role_v0006(login_role name,mapped_tenant uuid,mapped_principal uuid)",
  "function:keynes_internal.rotate_remote_role_v0006(old_login_role name,new_login_role name)",
  "function:keynes_internal.set_remote_role_enabled_v0006(login_role name,next_enabled boolean)",
  "function:keynes_internal.revoke_remote_role_v0006(login_role name)",
  "function:keynes_internal.inspect_remote_role_v0006(login_role name)",
  "function:keynes_internal.remote_dispatch_v0006(operation_name text,input jsonb)",
  "function:keynes_internal.get_budget(input jsonb)",
  "function:keynes.define_resource_type(input jsonb)",
  "function:keynes.create_budget(input jsonb)",
  "function:keynes.request(input jsonb)",
  "function:keynes.settle(input jsonb)",
  "function:keynes.get_budget(input jsonb)",
  "function:keynes.remote_create_budget(input jsonb)",
  "function:keynes.remote_request(input jsonb)",
  "function:keynes.remote_settle(input jsonb)",
  "function:keynes.remote_get_budget(input jsonb)",
  "function:keynes.remote_get_budget_history_page(input jsonb)",
  "function:keynes.remote_open_budget(input jsonb)",
  "function:keynes.remote_recover_operation(input jsonb)",
  "function:keynes.remote_get_compatibility(input jsonb)",
] as const;

export function expectedPostgresObjects(
  profile: LoadedPolicyProfile,
): readonly string[] {
  return [
    ...EXPECTED_POSTGRES_OBJECTS,
    ...policyFunctionSignatures(profile).map(
      (signature) => `function:keynes_internal.${signature}`,
    ),
  ];
}

function policyFunctionSignatures(
  profile: LoadedPolicyProfile,
): readonly string[] {
  return [
    "apply_command_legacy(operation_name text,input jsonb)",
    "policy_canonical_json(value jsonb)",
    "canonical_policy_set(policies jsonb)",
    "policy_sum(input_values numeric[])",
    "policy_avg(input_values numeric[])",
    "policy_runtime_numeric(value numeric)",
    "invalid_policy(issue_path text,issue_rule text)",
    "policy_assert_exact_keys(value jsonb,expected_keys text[],issue_path text)",
    "validate_policy_descriptor(value jsonb,descriptor jsonb,issue_path text)",
    "validate_policy_node(node jsonb)",
    "render_policy_node(node jsonb)",
    "validate_policy_program(program jsonb)",
    "render_policy_program(program jsonb)",
    "canonical_policy_expression(node jsonb)",
    "canonical_policy_parenthesize(node jsonb)",
    "canonical_policy_sql(program jsonb)",
    "policy_work_bound(program jsonb,requested_rows integer,available_rows integer)",
    "validate_policy_set(policies jsonb)",
    "validate_policy_context(policies jsonb,context jsonb)",
    "evaluate_policy_set(selected_tenant uuid,selected_budget uuid,policies jsonb,requested_items jsonb,context jsonb)",
    "check_policy_canonical_vectors()",
    ...profile.nodeKinds.flatMap((kind) => {
      const backend = profile.source.nodes[kind]?.backends.postgresql;
      if (backend === undefined) {
        throw new Error(`Policy node ${kind} lacks PostgreSQL metadata`);
      }
      return [
        `${backend.validator}(node jsonb)`,
        `${backend.renderer}(node jsonb)`,
      ];
    }),
  ];
}
