const EXPECTED_POSTGRES_OBJECTS = [
  "schema:keynes_internal",
  "schema:keynes",
  "table:keynes_internal.schema_migrations",
  "table:keynes_internal.installation_identity",
  "table:keynes_internal.principal_permissions",
  "table:keynes_internal.commands",
  "table:keynes_internal.resource_types",
  "table:keynes_internal.budgets",
  "table:keynes_internal.budget_resources",
  "table:keynes_internal.quantity_movements",
  "trigger:keynes_internal.quantity_movements_append_only:keynes_internal.quantity_movements:keynes_internal.guard_quantity_movement():O:31:none",
  "table:keynes_internal.budget_history_streams",
  "table:keynes_internal.budget_history_entries",
  "table:keynes_internal.remote_role_mappings",
  "table:keynes_internal.remote_credential_audit",
  "table:keynes_internal.remote_budget_references",
  "table:keynes_internal.remote_operations",
  "table:keynes_internal.remote_inspection_snapshots",
  "function:keynes_internal.raise_domain_error(error_code text,error_details jsonb)",
  "function:keynes_internal.checkpoint(checkpoint_name text)",
  "function:keynes_internal.invalid_command(operation_name text,issue_path text,issue_rule text)",
  "function:keynes_internal.canonical_decision_evidence(operation_name text,value jsonb,issue_path text)",
  "function:keynes_internal.canonical_envelope(operation_name text,value jsonb,issue_path text,allow_null boolean)",
  "function:keynes_internal.event_uuid(seed text)",
  "function:keynes_internal.subtree_observed(selected_tenant uuid,selected_budget uuid,selected_resource uuid)",
  "function:keynes_internal.budget_live(selected_tenant uuid,selected_budget uuid,selected_resource uuid)",
  "function:keynes_internal.assert_safe_accounting(selected_tenant uuid,changed_budget uuid,operation_name text)",
  "function:keynes_internal.budget_projection(selected_tenant uuid,selected_budget uuid)",
  "function:keynes_internal.budget_inspection_projection(selected_tenant uuid,selected_budget uuid)",
  "function:keynes_internal.inspection_history_entry_v0009(selected_tenant uuid,selected_stream uuid,terminal_sequence bigint,selected_sequence bigint,selected_command uuid,selected_kind text,selected_subject uuid,value_json jsonb)",
  "function:keynes_internal.finalize_budget_v0009(selected_tenant uuid,selected_budget uuid,selected_command uuid)",
  "function:keynes_internal.finalize_ready_ancestors_v0009(selected_tenant uuid,selected_budget uuid,selected_command uuid)",
  "function:keynes_internal.guard_quantity_movement()",
  "function:keynes_internal.append_history(selected_tenant uuid,selected_stream uuid,selected_command uuid,selected_kind text,selected_subject uuid,details jsonb)",
  "function:keynes_internal.apply_command(operation_name text,input jsonb)",
  "function:keynes_internal.canonical_resource_definition_v0008(operation_name text,value jsonb,issue_path text)",
  "function:keynes_internal.apply_command_legacy(operation_name text,input jsonb)",
  "function:keynes_internal.remote_error_v0006(error_code text,operation_name text)",
  "function:keynes_internal.remote_token_v0006(token_prefix text,token_seed text)",
  "function:keynes_internal.set_remote_identity_v0006()",
  "function:keynes_internal.remote_budget_reference_v0006(selected_tenant uuid,selected_budget uuid)",
  "function:keynes_internal.remote_budget_id_v0006(selected_tenant uuid,reference_value text,operation_name text)",
  "function:keynes_internal.remote_resource_id_v0006(selected_tenant uuid,resource_name text,operation_name text)",
  "function:keynes_internal.remote_named_amounts_v0006(selected_tenant uuid,selected_budget uuid,values_json jsonb,operation_name text,input_field text,allow_empty boolean)",
  "function:keynes_internal.remote_project_json_v0006(selected_tenant uuid,value_json jsonb)",
  "function:keynes_internal.remote_safe_error_v0006(operation_name text,error_json jsonb)",
  "function:keynes_internal.remote_invalid_v0006(operation_name text,issue_path text,issue_rule text)",
  "function:keynes_internal.remote_operation_lock_key_v0006(selected_tenant uuid,operation_key_value text)",
  "function:keynes_internal.remote_validate_input_v0006(operation_name text,input jsonb)",
  "function:keynes_internal.remote_history_amounts_v0006(selected_tenant uuid,values_json jsonb)",
  "function:keynes_internal.remote_inspection_projection_v0006(selected_tenant uuid,selected_budget uuid,selected_reference text)",
  "function:keynes_internal.remote_inspection_history_entry_v0006(selected_tenant uuid,value_json jsonb)",
  "function:keynes_internal.remote_get_budget_v0006(input jsonb)",
  "function:keynes_internal.remote_get_budget_history_page_v0006(input jsonb)",
  "function:keynes_internal.remote_open_budget_v0006(input jsonb)",
  "function:keynes_internal.remote_recover_operation_v0006(input jsonb)",
  "function:keynes_internal.remote_login_oid_v0006(login_role name)",
  "function:keynes_internal.register_remote_role_v0006(login_role name,mapped_tenant uuid,mapped_principal uuid)",
  "function:keynes_internal.rotate_remote_role_v0006(old_login_role name,new_login_role name)",
  "function:keynes_internal.set_remote_role_enabled_v0006(login_role name,next_enabled boolean)",
  "function:keynes_internal.revoke_remote_role_v0006(login_role name)",
  "function:keynes_internal.inspect_remote_role_v0006(login_role name)",
  "function:keynes_internal.audit_remote_role_v0006(login_role name,entry_limit integer)",
  "function:keynes_internal.remote_dispatch_v0006(operation_name text,input jsonb)",
  "function:keynes_internal.get_budget(input jsonb)",
  "function:keynes.define_resource_type(input jsonb)",
  "function:keynes.create_budget(input jsonb)",
  "function:keynes.request(input jsonb)",
  "function:keynes.settle(input jsonb)",
  "function:keynes.get_budget(input jsonb)",
  "function:keynes.remote_create_budget(input jsonb)",
  "function:keynes.remote_request(input jsonb)",
  "function:keynes.remote_settle(input jsonb)",
  "function:keynes.remote_get_budget(input jsonb)",
  "function:keynes.remote_get_budget_history_page(input jsonb)",
  "function:keynes.remote_open_budget(input jsonb)",
  "function:keynes.remote_recover_operation(input jsonb)",
  "function:keynes.remote_get_compatibility(input jsonb)",
  "function:keynes_internal.canonical_definitions_v0008(operation_name text,value jsonb)",
  "function:keynes_internal.resolve_resource_v0008(selected_tenant uuid,selected_principal uuid,selected_command uuid,selected_resource uuid,canonical_definition jsonb)",
  "function:keynes_internal.apply_define_resources_v0008(input jsonb)",
  "function:keynes_internal.apply_define_resource_v0008(input jsonb)",
  "function:keynes_internal.remote_define_resources_v0008(input jsonb)",
  "function:keynes.define_resources(input jsonb)",
  "function:keynes.remote_define_resources(input jsonb)",
  "function:keynes_internal.remote_get_compatibility_v0008(input jsonb)",
  "function:keynes_internal.canonical_creation_v0008(definitions_value jsonb,amounts_value jsonb)",
  "function:keynes_internal.apply_create_budget_v0008(input jsonb)",
  "function:keynes_internal.remote_create_budget_v0008(input jsonb)",
  "function:keynes_internal.remote_recover_operation_v0008(input jsonb)",
  "function:keynes_internal.remote_apply_command_v0008(operation_name text,input jsonb)",
  "function:keynes_internal.validate_resources_v0008(input jsonb)",
  "function:keynes_internal.remote_validate_resources_v0008(input jsonb)",
  "function:keynes.validate_resources(input jsonb)",
  "function:keynes.remote_validate_resources(input jsonb)",
] as const;

export function expectedPostgresObjects(): readonly string[] {
  return EXPECTED_POSTGRES_OBJECTS;
}
