import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  applyGeneratedOutputs,
  type ContractSource,
  type LoadedContract,
} from "@keynes/contracts";
import { format } from "oxfmt";

export interface CloudInstallationIdentity {
  readonly contractMigrationId: string;
  readonly migrations: readonly {
    readonly id: string;
    readonly sha256: string;
  }[];
}

export interface GenerateCloudOptions {
  readonly check: boolean;
  readonly contract: LoadedContract;
  readonly installation: CloudInstallationIdentity;
  readonly repositoryRoot?: string;
}

export async function generateCloud(
  options: GenerateCloudOptions,
): Promise<void> {
  const repositoryRoot =
    options.repositoryRoot ??
    fileURLToPath(new URL("../../../", import.meta.url));
  const procedures = await formatSource(
    "procedures.ts",
    renderCloudProcedures(
      options.contract.source,
      options.contract.digest,
      options.installation,
    ),
  );
  applyGeneratedOutputs({
    check: options.check,
    outputRoot: resolve(repositoryRoot, "apps/cloud"),
    outputs: new Map([["src/generated/procedures.ts", procedures]]),
    generatedDirectories: [{ path: "src/generated", accepts: () => true }],
  });
}

function renderCloudProcedures(
  contract: ContractSource,
  digest: string,
  installation: CloudInstallationIdentity,
): string {
  const installationMigrations = installation.migrations
    .map((migration) => {
      const contractDigest =
        migration.id === installation.contractMigrationId ? digest : null;
      return `  {\n    id: ${JSON.stringify(migration.id)},\n    byteChecksum: ${JSON.stringify(migration.sha256)},\n    contractDigest: ${JSON.stringify(contractDigest)},\n  },`;
    })
    .join("\n");
  const procedures = contract.operations
    .map(
      (operation) =>
        `  ${operation.method}: {\n    target: ${JSON.stringify(operation.target)},\n    statement: ${JSON.stringify(`select ${operation.target}($1::jsonb) as response`)},\n    permissions: ${JSON.stringify(operation.permissions)},\n    replay: ${String(operation.replay)},\n  },`,
    )
    .join("\n");

  return `// Generated by scripts/generate-contracts.ts. Do not edit.\n\nexport const CONTRACT_DIGEST = ${JSON.stringify(digest)};\n\nexport const INSTALLATION_MIGRATIONS = [\n${installationMigrations}\n] as const;\n\nexport const PROCEDURES = {\n${procedures}\n} as const;\n\nexport type OperationName = keyof typeof PROCEDURES;\n`;
}

async function formatSource(path: string, source: string): Promise<string> {
  const result = await format(
    path,
    source.replace(
      "// Generated by scripts/generate-contracts.ts. Do not edit.",
      "// Generated from contracts/. Do not edit.",
    ),
    { printWidth: 80 },
  );
  const error = result.errors.find(
    (diagnostic) => diagnostic.severity === "Error",
  );
  if (error !== undefined) {
    throw new Error(
      `cannot format generated ${path}: ${error.message ?? "parse error"}`,
    );
  }
  return result.code;
}
