export const REQUIRED_LOCAL_SCENARIOS: Readonly<
  Record<string, readonly string[]>
> = {
  "packages/sdk/test/contract/budget.test.ts": [
    "Budget lifecycle defines a Resource type without creating Budget quantity",
    "Budget lifecycle preserves definition identity and distinguishes replay from redefinition",
    "Budget lifecycle returns canonical Resource definition errors",
    "Budget lifecycle completes one funded child lifecycle and reads its root-lineage history",
    "command replay recovers all four canonical results across principals without duplicate history",
    "command replay replays a structurally equal command across principals despite object key order",
    "command replay recovers Resource definition after its committed response is lost",
    "command replay recovers root allocation after its committed response is lost",
    "command replay recovers an approved request after its committed response is lost",
    "command replay recovers settlement after its committed response is lost",
    "command replay rejects changed bodies for each mutation, including across principals",
    "command replay rejects reuse by a different operation",
    "command replay rejects reuse against a different target",
    "Budget request denial denies one unavailable Resource without changing the parent",
    "Budget request denial denies a multi-Resource envelope without reserving its fundable part",
    "Budget request denial conserves 100 sibling overlaps through public serialization, not multi-connection contention",
    "Budget request denial rejects malformed, duplicate, and caller-selected funding envelopes",
    "Budget request denial rejects a Resource type that has not been defined before evaluating funding",
    "Budget request denial rejects a request after its parent becomes inactive",
    "Budget request denial keeps request, settlement, and read permissions independent",
    "Resource-bound root creation binds Resource definitions, allocations, and creation history in one root command",
    "Resource-bound root creation replays an identical combined root command without duplicating history",
    "Resource-bound root creation rejects a changed definition-bearing root body under the same command identity",
    "Resource-bound root creation commits an attached Policy with the Resource-bound root",
    "Resource-bound root creation rolls back definitions, root state, and history after Resource insertion",
    "command rollback rolls back Resource definition checkpoints",
    "command rollback rolls back root allocation facts, result, and history",
    "command rollback rolls back child reservation, result, and history",
    "command rollback rolls back usage, result, and settlement history",
    "Budget settlement keeps a sealed parent settling until its open descendant settles",
    "Budget settlement resolves missing usage and records an exact known repeat as a no-op",
    "Budget settlement returns a reusable child allocation in full after settlement",
    "Budget settlement isolates child overage without charging its parent or sibling",
    "Budget settlement bounds settled nested charges before returning them to an ancestor",
    "Budget settlement settles a subset while keeping an omitted Resource unresolved",
    "Budget settlement sorts multiple isolated deficits by Resource identity",
    "Budget settlement rejects derived arithmetic overflow without committing settlement",
  ],
  "packages/sdk/test/unit/local/local-lifecycle.test.ts": [
    "local runtime lifecycle serializes overlapping calls and drains admitted work before close",
    "local runtime lifecycle shares one close promise and rejects new Keynes and Budget work immediately",
    "local runtime lifecycle drains an admitted domain error and inspection before closing",
    "local runtime lifecycle shares one failed close result and remains closed",
    "local runtime lifecycle keeps two local runtimes isolated",
    "local runtime lifecycle constructs the local runtime with one SQLite command executor",
    "local runtime lifecycle rolls back a Resource definition when root creation fails",
    "local runtime lifecycle retains a SQLite schema initialization failure",
    "local runtime lifecycle retains SQLite schema initialization and cleanup failures",
  ],
  "packages/sdk/test/unit/local/local-replay.test.ts": [
    "local facade committed-response replay replays one lost createBudget response with the exact command object",
    "local facade committed-response replay replays one lost requestBudget response with the exact command object",
    "local facade committed-response replay replays one lost settleBudget response with the exact command object",
    "local facade committed-response replay maps a second lost response to operation_interrupted",
    "local facade committed-response replay creates a distinct command identity for each public call",
  ],
  "packages/sdk/test/unit/local/policy-fail-closed.test.ts": [
    "local Policy evaluation failures rejects a digest-correct artifact whose canonical SQL does not match its program",
    "local Policy evaluation failures rejects a direct Policy artifact whose outputs are not inputs",
    "local Policy evaluation failures enforces the generated work limit",
    "local Policy evaluation failures returns a sanitized arithmetic_overflow failure without changing Budget state",
    "local Policy evaluation failures returns a sanitized numeric_domain failure without changing Budget state",
    "local Policy evaluation failures returns a sanitized invalid_result failure without changing Budget state",
    "local Policy evaluation failures maps evaluator-owned numeric_precision failures",
    "local Policy evaluation failures maps evaluator-owned execution_failed failures",
    "local Policy evaluation failures fails the whole command when one Policy succeeds and another fails",
    "governed SQLite mutation rollback removes failed Policy command binding so the identity can be retried",
    "governed SQLite mutation rollback rolls back after_command_binding",
    "governed SQLite mutation rollback rolls back after_policy_evaluation",
    "governed SQLite mutation rollback rolls back after_domain_mutation",
    "governed SQLite mutation rollback rolls back after_history_insertion",
    "governed SQLite mutation rollback rolls back after_result_storage",
  ],
  "packages/sdk/test/unit/local/policy-replay.test.ts": [
    "local governed request replay returns stored evidence before a changed evaluator profile and mutates nothing",
    "local governed request replay keeps the original decision after availability and an unrelated revision change",
    "local governed request replay canonicalizes Context key order but conflicts on a changed value",
    "local governed request replay canonicalizes child Policy order and conflicts on a changed definition",
    "local governed request replay treats omitted and explicit empty child Policy sets as one command",
  ],
  "packages/sdk/test/unit/local/policy-request.test.ts": [
    "local governed Budget requests evaluates requested, availability, and Context through the public Budget path",
    "local governed Budget requests uses available Resources when they are the Policy ceiling",
    "local governed Budget requests approves atomically and reserves the exact requested quantity",
    "local governed Budget requests denies above the Policy ceiling without changing holdings",
    "local governed Budget requests detaches and records the exact canonical context",
    "local governed Budget requests uses the lowest ceiling and retains every tied Policy reason",
    "local governed Budget requests orders Policy evidence and Resources by PostgreSQL C bytes",
    "local governed Budget requests returns identical canonical evidence in the result and history",
    "local governed Budget requests attaches only explicitly supplied child Policies",
    "local governed Budget requests attaches child Policies from an ungoverned Budget",
    "local governed Budget requests rejects the legacy request key and names invalid child Policies",
    "local governed Budget requests does not inherit parent Policies into an approved child",
    "local governed Budget requests rolls back when any parent Policy evaluation fails",
  ],
  "packages/sdk/test/unit/local/sqlite-command-executor.test.ts": [
    "SQLite command executor initializes a schema that supports all five fixed-statement operations",
    "SQLite command executor round-trips Number.MAX_SAFE_INTEGER through SQLite INTEGER reads",
    "SQLite command executor matches the PostgreSQL jsonb Resource definition digest",
    "SQLite command executor keeps mutation replay state on the wire envelope",
    "SQLite command executor rolls back the immediate transaction after after_command_binding",
    "SQLite command executor rolls back the immediate transaction after after_resource_insertion",
    "SQLite command executor rolls back the immediate transaction after after_domain_mutation",
    "SQLite command executor rolls back the immediate transaction after after_history_insertion",
    "SQLite command executor rolls back the immediate transaction after after_result_storage",
    "SQLite command executor rejects malformed direct defineResource input without state change or a transaction",
    "SQLite command executor rejects malformed direct createBudget input without state change or a transaction",
    "SQLite command executor rejects malformed direct requestBudget input without state change or a transaction",
    "SQLite command executor rejects malformed direct settleBudget input without state change or a transaction",
    "SQLite command executor rejects malformed direct getBudget input without state change or a transaction",
  ],
  "packages/sdk/test/unit/local/sqlite-store.test.ts": [
    "SQLite store opens only an in-memory database with extension loading disabled",
    "SQLite store closes the acquired database when schema initialization fails",
    "SQLite store fails explicitly when node:sqlite is unavailable",
  ],
  "packages/sdk/test/unit/policy/authoring.test.ts": [
    "Policy authoring normalizes Kysely callbacks, Kysely sql, raw SQL, and parameters to one definition",
    "Policy authoring includes the revision in definition identity but not source identity",
    "Policy authoring deeply freezes Policy definitions and sets",
    "Policy authoring returns public path and rule diagnostics for authoring rejection",
    "Policy authoring rejects malformed declaration 0",
    "Policy authoring rejects malformed declaration 1",
    "Policy authoring rejects malformed declaration 2",
    "Policy authoring rejects malformed declaration 3",
    "Policy authoring rejects malformed declaration 4",
    "Policy authoring rejects malformed declaration 5",
    "Policy authoring rejects malformed declaration 6",
    "Policy authoring rejects malformed declaration 7",
    "Policy authoring rejects malformed declaration 8",
    "Policy authoring rejects malformed declaration 9",
    "Policy authoring rejects malformed declaration 10",
    "Policy authoring rejects malformed declarations before invoking the query callback",
    "Policy authoring preserves errors thrown by the adopter's query callback",
    "Policy authoring preserves errors thrown while compiling the adopter's Kysely query",
    "Policy authoring reports the exact Kysely parameter path",
  ],
  "packages/sdk/test/unit/policy/evaluate.test.ts": [
    "local Policy interpreter executes every shared runtime test program",
    "local Policy interpreter executes every generated scalar canonical vector",
    "local Policy interpreter rounds every arithmetic boundary to numeric(38,18)",
    "local Policy interpreter uses PostgreSQL three-valued null logic",
    "local Policy interpreter does not evaluate unreachable coalesce arguments",
    "local Policy interpreter groups, aggregates, and canonically orders result rows",
    "local Policy interpreter enforces result-row and deterministic operation limits",
    "local Policy interpreter returns only valid Policy result rows",
  ],
  "packages/sdk/test/unit/policy/parser.test.ts": [
    "PostgreSQL 18 Policy parser adapter accepts one Policy SELECT and carries a detached positional parameter vector",
    "PostgreSQL 18 Policy parser adapter accepts line and block comments as PostgreSQL syntax trivia",
    "PostgreSQL 18 Policy parser adapter rejects PostgreSQL parse errors",
    "PostgreSQL 18 Policy parser adapter rejects more than one parsed statement",
    "PostgreSQL 18 Policy parser adapter rejects a 'quoted identifier'",
    "PostgreSQL 18 Policy parser adapter rejects a 'escape string'",
    "PostgreSQL 18 Policy parser adapter rejects a 'dollar-quoted string'",
    "PostgreSQL 18 Policy parser adapter rejects a non-SELECT InsertStmt top-level parser node",
    "PostgreSQL 18 Policy parser adapter rejects a non-SELECT UpdateStmt top-level parser node",
    "PostgreSQL 18 Policy parser adapter rejects a non-SELECT DeleteStmt top-level parser node",
    "PostgreSQL 18 Policy parser adapter rejects a non-SELECT CreateStmt top-level parser node",
    "PostgreSQL 18 Policy parser adapter rejects a non-SELECT ExplainStmt top-level parser node",
  ],
  "packages/sdk/test/unit/policy/rejection.test.ts": [
    "Policy source rejection rejects the syntax parser node",
    "Policy source rejection rejects the multiple statements parser node",
    "Policy source rejection rejects the INSERT parser node",
    "Policy source rejection rejects the UPDATE parser node",
    "Policy source rejection rejects the DELETE parser node",
    "Policy source rejection rejects the MERGE parser node",
    "Policy source rejection rejects the CREATE parser node",
    "Policy source rejection rejects the ALTER parser node",
    "Policy source rejection rejects the DROP parser node",
    "Policy source rejection rejects the TRUNCATE parser node",
    "Policy source rejection rejects the transaction parser node",
    "Policy source rejection rejects the session parser node",
    "Policy source rejection rejects the COPY parser node",
    "Policy source rejection rejects the EXPLAIN parser node",
    "Policy source rejection rejects the procedure parser node",
    'Policy source rejection rejects unsupported lexical source SELECT "requested".resource',
    'Policy source rejection rejects unsupported lexical source SELECT U&"requested".resource',
    "Policy source rejection rejects unsupported lexical source SELECT E'escaped'",
    "Policy source rejection rejects unsupported lexical source SELECT U&'escaped'",
    "Policy source rejection rejects unsupported lexical source SELECT $$escaped$$",
    "Policy source rejection rejects unsupported SELECT shape: star projection",
    "Policy source rejection rejects unsupported SELECT shape: WITH",
    "Policy source rejection rejects unsupported SELECT shape: DISTINCT",
    "Policy source rejection rejects unsupported SELECT shape: scalar subquery",
    "Policy source rejection rejects unsupported SELECT shape: UNION",
    "Policy source rejection rejects unsupported SELECT shape: HAVING",
    "Policy source rejection rejects unsupported SELECT shape: LIMIT",
    "Policy source rejection rejects unsupported SELECT shape: OFFSET",
    "Policy source rejection rejects unsupported SELECT shape: window",
    "Policy source rejection rejects source beyond the profile byte limit",
    "Policy source rejection rejects an aggregate in the first CASE condition",
    "Policy source rejection rejects an aggregate in the later CASE condition",
    "Policy source rejection rejects an aggregate in the first CASE result",
    "Policy source rejection rejects an aggregate in the later CASE result",
    "Policy source rejection rejects an aggregate in the CASE else result",
    "Policy source rejection rejects an aggregate in the nested second coalesce argument",
    "Policy source rejection rejects an aggregate in the nested later coalesce argument",
    "Policy source rejection accepts an aggregate in first coalesce argument",
    "Policy source rejection accepts an aggregate in least",
    "Policy source rejection accepts an aggregate in greatest",
    "Policy source rejection rejects a direct normalized aggregate in a CASE condition",
    "Policy source rejection rejects a direct normalized aggregate in a CASE result",
    "Policy source rejection rejects a direct normalized aggregate in a CASE else",
    "Policy source rejection rejects a direct normalized aggregate in a second coalesce argument",
    "Policy source rejection accepts a direct normalized aggregate in first coalesce argument",
    "Policy source rejection accepts a direct normalized aggregate in least",
    "Policy source rejection accepts a direct normalized aggregate in greatest",
    "Policy source rejection rejects an unsupported catalog relation",
    "Policy source rejection rejects an unsupported application relation",
    "Policy source rejection rejects an unsupported unknown function",
    "Policy source rejection rejects an unsupported qualified function",
    "Policy source rejection rejects an unsupported concatenation operator",
    "Policy source rejection rejects an unsupported pattern operator",
    "Policy source rejection rejects an unsupported explicit cast",
    "Policy source rejection rejects an unsupported COLLATE",
    "Policy source rejection rejects unsafe Kysely identifiers before parsing",
    "Policy source rejection rejects a missing parameter vector",
    "Policy source rejection rejects a unused parameter vector",
    "Policy source rejection rejects a conflicting type parameter vector",
    "Policy source rejection rejects a non-finite parameter vector",
    "Policy source rejection rejects excess and non-scalar parameter vectors",
    "Policy source rejection omits comments and comment contents from Policy identity",
  ],
  "packages/sdk/test/unit/policy/source-behavior.test.ts": [
    "Policy source behavior normalizes every accepted source fixture through the public authoring boundary",
    "Policy source behavior rejects every disallowed source fixture through the public authoring boundary",
  ],
  "packages/sdk/test/unit/public/budget-projection.test.ts": [
    "public Budget projections orders Resource-bearing output by public key across private identity orders",
  ],
  "packages/sdk/test/unit/public/generated-client.test.ts": [
    "generated client bindings binds every concrete method to its deployment-neutral operation",
    "generated client bindings validates input before dispatch",
    "generated client bindings rejects an invalid wire envelope before returning it, case 0",
    "generated client bindings rejects an invalid wire envelope before returning it, case 1",
    "generated client bindings rejects an invalid wire envelope before returning it, case 2",
    "generated client bindings rejects an invalid wire envelope before returning it, case 3",
    "generated client bindings rejects an invalid wire envelope before returning it, case 4",
    "generated client bindings rejects an invalid wire envelope before returning it, case 5",
    "generated client bindings detaches validated output from the executor wire value",
    "generated client bindings sorts validation issues independently of property insertion order",
    "generated client bindings rejects structurally duplicate resource entries regardless of property order",
  ],
  "packages/sdk/test/unit/public/local.test.ts": [
    "local Keynes facade opens without setup Resources and binds only allocated schema entries",
    "local Keynes facade reuses exact definitions and rolls back a conflicting root",
    "local Keynes facade keeps independent roots isolated and ignores unallocated schema entries",
    "local Keynes facade projects double-settlement conflicts without private identities",
    "local Keynes facade runs approval, denial, settlement, overage, and inspection through Budget handles",
    "local Keynes facade gives repeated schemas one identity and isolates conflicting definitions across runtimes",
    "local Keynes facade validates every Resource name before opening a runtime",
    "local Keynes facade rejects definition fields that could override the derived canonical name",
    "local Keynes facade returns a stable error for malformed Resource definitions 0",
    "local Keynes facade returns a stable error for malformed Resource definitions 1",
    "local Keynes facade keeps the installed Resource catalog detached from source definitions",
    "local Keynes facade keeps returned mutation results detached from retained local state",
    "local Keynes facade snapshots requested amounts before asynchronous admission",
    "local Keynes facade does not widen child Resource names from a later input mutation",
    "local Keynes facade snapshots settlement usage before asynchronous admission",
    "local Keynes facade does not widen settlement Resources from a later input mutation",
    "local Keynes facade keeps malformed child inputs inside the asynchronous error boundary",
    "local Keynes facade rejects Resources outside the root binding",
    "local Keynes facade rejects setup argument: explicit undefined",
    "local Keynes facade rejects setup argument: an empty object",
    "local Keynes facade rejects setup argument: an undefined Resource schema",
    "local Keynes facade rejects setup argument: a Resource schema",
    "local Keynes facade rejects setup argument: a PostgreSQL URL",
  ],
  "packages/sdk/test/unit/public/policy-api.test.ts": [
    "schema-first public API copies and deeply freezes the complete Resource schema",
    "schema-first public API returns frozen closure-backed handles with one shared close result",
  ],
  "packages/sdk/test/unit/public/public-exports.test.ts": [
    "package-root exports exports the local facade and accepted generated domain types",
    "package-root exports keeps Budget request keys within the handle's Resource names",
    "package-root exports opens without a schema and infers each root from its allocated schema entries",
  ],
};

export const LOCAL_TEST_FILES = Object.keys(REQUIRED_LOCAL_SCENARIOS);
